' <auto-generated>
'     webview2-bridge VB JSON-RPC runtime (namespace WebView2Bridge.Runtime; needs Newtonsoft.Json)
'     copied by @ishibashi0112/webview2-bridge-gen 0.6.0 from its bundled vb-runtime/runtime/.
'     DO NOT EDIT. Changes will be lost when `pnpm gen` runs.
'     To update, upgrade the npm package and run the generator again.
' </auto-generated>
Option Strict On

Imports System
Imports System.IO
Imports Newtonsoft.Json
Imports Newtonsoft.Json.Linq

Namespace Global.WebView2Bridge.Runtime

    ''' <summary>JSON-RPC 2.0 のエラーコード（HANDOFF.md §5）</summary>
    Public NotInheritable Class JsonRpcErrorCodes
        Private Sub New()
        End Sub

        Public Const ParseError As Integer = -32700
        Public Const InvalidRequest As Integer = -32600
        Public Const MethodNotFound As Integer = -32601
        Public Const InvalidParams As Integer = -32602
        Public Const InternalError As Integer = -32603
        ''' <summary>アプリ定義エラーの既定値。実装側の未処理例外はこのコードになる</summary>
        Public Const ServerError As Integer = -32000
        ''' <summary>
        ''' 業務エラー。message をそのまま利用者に見せてよい。data は省略か BusinessErrorData（{ "field": "要求の JSON 名" }）。
        ''' 投げるときは JsonRpcException.Business(message, field) を使う
        ''' </summary>
        Public Const Business As Integer = -32010
        ''' <summary>
        ''' 利用者向けエラーの範囲（-32019〜-32010）。この範囲の message は画面がそのまま利用者に見せる。
        ''' -32010 が汎用の業務エラー、-32011 以降はアプリが決める（例: ファイルに書き込めない）
        ''' </summary>
        Public Const UserFacingMin As Integer = -32019
        Public Const UserFacingMax As Integer = Business

        ''' <summary>code が利用者向け（-32019〜-32010）か</summary>
        Public Shared Function IsUserFacing(code As Integer) As Boolean
            Return code >= UserFacingMin AndAlso code <= UserFacingMax
        End Function
    End Class

    ''' <summary>業務エラー（-32010）の data。Field は結び付く入力項目（要求の JSON 名、camelCase）。無ければキーごと省く</summary>
    Public Class BusinessErrorData
        <JsonProperty("field", NullValueHandling:=NullValueHandling.Ignore)>
        Public Property Field As String
    End Class

    ''' <summary>
    ''' 実装（IXxxApi）から意図的に JSON-RPC エラーを返したいときに投げる。
    ''' Code は -32000 以下のアプリ定義コードを使う。利用者に見せる業務エラーは Business(message, field) で作る。
    ''' </summary>
    Public Class JsonRpcException
        Inherits Exception

        Public ReadOnly Property Code As Integer
        Public ReadOnly Property ErrorData As Object

        Public Sub New(code As Integer, message As String)
            Me.New(code, message, Nothing)
        End Sub

        Public Sub New(code As Integer, message As String, data As Object)
            MyBase.New(message)
            Me.Code = code
            Me.ErrorData = data
        End Sub

        ''' <summary>
        ''' 業務エラー（-32010）。message は利用者にそのまま見せる文。field は結び付く入力項目（要求の JSON 名）で、省略可。
        ''' 画面側は client の isBusinessError / errorField で受ける
        ''' </summary>
        Public Shared Function Business(message As String, Optional field As String = Nothing) As JsonRpcException
            Dim data As Object = If(String.IsNullOrEmpty(field), Nothing, New BusinessErrorData With {.Field = field})
            Return New JsonRpcException(JsonRpcErrorCodes.Business, message, data)
        End Function
    End Class

    ''' <summary>JSON-RPC 封筒の組み立て・解釈。Dispatcher と Host（WebViewBridge）が共用する</summary>
    Public NotInheritable Class JsonRpc
        Private Sub New()
        End Sub

        Public Const Version As String = "2.0"

        ''' <summary>
        ''' ブリッジ全体で使う Newtonsoft の設定。
        ''' DateParseHandling.None: "2024-01-01T00:00:00Z" のような文字列を Date に変換せず、文字列のまま往復させる。
        ''' </summary>
        Public Shared Function CreateSerializerSettings() As JsonSerializerSettings
            Return New JsonSerializerSettings() With {
                .DateParseHandling = DateParseHandling.None,
                .NullValueHandling = NullValueHandling.Include,
                .Formatting = Formatting.None
            }
        End Function

        ''' <summary>JSON 文字列 → JToken。日付文字列を自動変換しない</summary>
        Public Shared Function ParseToken(json As String) As JToken
            Using sr As New StringReader(json)
                Using reader As New JsonTextReader(sr)
                    reader.DateParseHandling = DateParseHandling.None
                    Dim token = JToken.ReadFrom(reader)
                    ' 末尾にゴミが無いことを確認する（"{}{}" のような入力を弾く）
                    If reader.Read() Then
                        Throw New JsonReaderException("Additional text found after JSON root")
                    End If
                    Return token
                End Using
            End Using
        End Function

        ''' <summary>成功応答 {"jsonrpc":"2.0","id":...,"result":...}</summary>
        Public Shared Function BuildResult(id As JToken, result As Object, serializer As JsonSerializer) As String
            Dim resultToken As JToken = If(result Is Nothing, CType(JValue.CreateNull(), JToken), JToken.FromObject(result, serializer))
            Dim o As New JObject() From {
                {"jsonrpc", Version},
                {"id", NormalizeId(id)},
                {"result", resultToken}
            }
            Return o.ToString(Formatting.None)
        End Function

        ''' <summary>エラー応答 {"jsonrpc":"2.0","id":...,"error":{"code","message","data"}}</summary>
        Public Shared Function BuildError(id As JToken, code As Integer, message As String, data As Object, serializer As JsonSerializer) As String
            Dim dataToken As JToken = If(data Is Nothing, CType(JValue.CreateNull(), JToken), JToken.FromObject(data, serializer))
            Dim err As New JObject() From {
                {"code", code},
                {"message", If(message, String.Empty)},
                {"data", dataToken}
            }
            Dim o As New JObject() From {
                {"jsonrpc", Version},
                {"id", NormalizeId(id)},
                {"error", err}
            }
            Return o.ToString(Formatting.None)
        End Function

        ''' <summary>通知 {"jsonrpc":"2.0","method":...,"params":...}（id なし）</summary>
        Public Shared Function BuildNotification(method As String, params As Object, serializer As JsonSerializer) As String
            If String.IsNullOrEmpty(method) Then Throw New ArgumentException("method is required", NameOf(method))
            Dim paramsToken As JToken = If(params Is Nothing, CType(JValue.CreateNull(), JToken), JToken.FromObject(params, serializer))
            Dim o As New JObject() From {
                {"jsonrpc", Version},
                {"method", method},
                {"params", paramsToken}
            }
            Return o.ToString(Formatting.None)
        End Function

        Private Shared Function NormalizeId(id As JToken) As JToken
            If id Is Nothing Then Return JValue.CreateNull()
            Return id.DeepClone()
        End Function
    End Class

End Namespace
