<Project>
  <PropertyGroup>
    <OptionStrict>On</OptionStrict>
    <OptionExplicit>On</OptionExplicit>
    <OptionInfer>On</OptionInfer>
    <LangVersion>16.9</LangVersion>
    <MyType Condition="'$(OutputType)' != 'WinExe'">Empty</MyType>
    <EnableWindowsTargeting Condition="'$(OS)' != 'Windows_NT'">true</EnableWindowsTargeting>
  </PropertyGroup>
</Project>
